remote_theme: mmistakes/minimal-mistakes@4.24.0

title: "WeatherLink Developer Portal"

url: "https://weatherlink.github.io"

# logo: /assets/vendor/weatherlink/images/logo_100.png

after_footer_scripts:
  - /assets/vendor/weatherlink/js/author.js
  - /assets/vendor/weatherlink/js/footer-copyright.js

include:
  - _pages

plugins:
  - jekyll-include-cache
